# Generated by Django 4.1.7 on 2023-02-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docuemnts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre local')),
                ('use', models.CharField(max_length=100, verbose_name='Uso')),
                ('image', models.ImageField(upload_to='tickets', verbose_name='Imagen')),
                ('type', models.ManyToManyField(to='bills.docuemnts')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre local')),
                ('address', models.CharField(max_length=100, verbose_name='Nombre')),
                ('giro', models.CharField(max_length=30, verbose_name='Nombre')),
                ('use', models.CharField(max_length=100, verbose_name='Uso')),
                ('image', models.ImageField(upload_to='bills', verbose_name='Imagen')),
                ('type', models.ManyToManyField(to='bills.docuemnts')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
