# Generated by Django 4.1.7 on 2023-02-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_bills_type_remove_tickets_type_bills_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuemnts',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Tipo'),
        ),
    ]
