# Generated by Django 4.1.7 on 2023-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_workers_alter_bills_options_alter_docuemnts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='cash',
            field=models.PositiveIntegerField(default=2000, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docuemnts',
            name='type',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tipo'),
        ),
    ]
