# Generated by Django 4.1.7 on 2023-02-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_tickets_cash_alter_docuemnts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='iva',
            field=models.PositiveIntegerField(null=True, verbose_name='Iva'),
        ),
        migrations.AddField(
            model_name='bills',
            name='neto',
            field=models.PositiveIntegerField(null=True, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='bills',
            name='total',
            field=models.PositiveIntegerField(null=True, verbose_name='Total'),
        ),
    ]
