# Generated by Django 4.1.7 on 2023-02-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_bills_iva_bills_neto_bills_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='neto',
            field=models.PositiveIntegerField(verbose_name='Neto'),
        ),
    ]
