# Generated by Django 4.1.7 on 2023-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_bills_neto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='iva',
            field=models.PositiveIntegerField(verbose_name='Iva'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total'),
        ),
    ]
