# Generated by Django 4.1.7 on 2023-02-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=30)),
                ('altitude', models.IntegerField()),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('last_update', models.IntegerField()),
                ('normal_bikes', models.IntegerField()),
                ('payment', models.IntegerField(choices=[(1, 'Key'), (2, 'transitcard'), (3, 'creditcard'), (4, 'phone')])),
                ('payment_terminal', models.BooleanField()),
                ('post_code', models.CharField(max_length=10)),
                ('renting', models.IntegerField()),
                ('returning', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('uid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('contry', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_station', models.IntegerField()),
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('id_token', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('extras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro1.extras')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbfs_href', models.CharField(max_length=100)),
                ('hrref', models.CharField(max_length=50)),
                ('id_ref', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('company', models.ManyToManyField(to='pro1.company')),
                ('location', models.ManyToManyField(to='pro1.location')),
                ('station', models.ManyToManyField(to='pro1.station')),
            ],
        ),
    ]
