# Generated by Django 4.1.7 on 2023-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
