# Generated by Django 4.1.7 on 2023-02-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0005_remove_network_company_remove_network_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='number_station',
        ),
    ]
