# Generated by Django 4.1.7 on 2023-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0006_remove_station_number_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_pay', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='number_station',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='extras',
            name='payment',
        ),
        migrations.AddField(
            model_name='extras',
            name='payment',
            field=models.ManyToManyField(to='pro1.payment'),
        ),
    ]
