# Generated by Django 4.1.7 on 2023-02-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0009_alter_extras_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='addres',
            field=models.CharField(max_length=100),
        ),
    ]
