# Generated by Django 4.1.7 on 2023-02-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro1', '0010_alter_extras_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='uid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
