# Generated by Django 4.1.7 on 2023-02-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('edad', models.PositiveIntegerField(verbose_name='edad')),
            ],
        ),
    ]
