# Generated by Django 4.1.6 on 2023-02-10 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15, verbose_name='Marca')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('image', models.ImageField(upload_to='sensors', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sensor N', max_length=10, verbose_name='Nombre')),
                ('locate', models.CharField(max_length=15, verbose_name='Instalado en')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.FloatField(verbose_name='Voltaje L1 - N')),
                ('v2', models.FloatField(verbose_name='Voltaje L2 - N')),
                ('v3', models.FloatField(verbose_name='Voltaje L3 - N')),
                ('v13', models.FloatField(verbose_name='Voltaje L1 - L3')),
                ('v23', models.FloatField(verbose_name='Voltaje L2 - L3')),
                ('i1', models.FloatField(verbose_name='Corriente L1')),
                ('i2', models.FloatField(verbose_name='Corriente L2')),
                ('i3', models.FloatField(verbose_name='Corriente L3')),
                ('p1', models.FloatField(verbose_name='Potencia L1')),
                ('p2', models.FloatField(verbose_name='Potencia L2')),
                ('p3', models.FloatField(verbose_name='Potencia L3')),
                ('pa', models.FloatField(verbose_name='Potencia Activa')),
                ('fp', models.FloatField(verbose_name='Factor de potencia')),
                ('hz', models.FloatField(verbose_name='Frecuencia')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Ingresado')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
    ]
