# Generated by Django 4.1.6 on 2023-02-13 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipo', to='sensors.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='locate',
            field=models.CharField(max_length=20, verbose_name='Instalado en'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='Sensor N', max_length=10, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Ingresado'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sensor', to='sensors.sensor', verbose_name='Sensor'),
        ),
    ]
