# Generated by Django 4.1.6 on 2023-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_equipo_alter_sensor_locate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='v12',
            field=models.FloatField(default=400.6, verbose_name='Voltaje L1 - L2'),
            preserve_default=False,
        ),
    ]
