# Generated by Django 4.1.6 on 2023-02-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_variable_v12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='sensors.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensors.sensor', verbose_name='Sensor'),
        ),
    ]
