# Generated by Django 4.1.6 on 2023-02-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_equipo_alter_variable_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Ingresado'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensors.sensor', verbose_name='sensor'),
        ),
    ]
